before:
  hooks:
  - go mod download

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ .Tag }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^chore'

release:
  disable: false

sboms:
-
  artifacts: archive

builds:
-
  id: cli
  dir: ./cmd/
  env: [CGO_ENABLED=0]
  ldflags: [-w -s -extldflags "-static"]
  goos: [windows]
  goarch: [amd64, arm64]
  binary: totalrecall

archives:
-
  name_template: "totalrecall_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
  format: zip